# First use inkscape to make a 300 dpi png, with export area set to "Page," then:

default:
	convert cover.png -background white -alpha remove -flatten -alpha off cover_no_transparency.png

clean:
	rm -f cover.png cover_no_transparency.png
